"""initial_schema

Revision ID: ee345c9db243
Revises: 
Create Date: 2026-10-10 23:30:47.132258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee345c9db243'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_refund_order', 'refunds', ['order_id'])
    op.create_unique_constraint('uq_return_order_item', 'returns', ['order_id', 'order_item_id'])
    op.create_index(op.f('ix_support_tickets_conversation_id'), 'support_tickets', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_tickets_conversation_id'), table_name='support_tickets')
    op.drop_constraint('uq_return_order_item', 'returns', type_='unique')
    op.drop_constraint('uq_refund_order', 'refunds', type_='unique')
    # ### end Alembic commands ###
